---
- hosts: localhost
  connection: local
  become: false

  vars:
    transmission_retention: 30
    transmission_host: localhost
    transmission_port: 9091
    transmission_root: /jewflix/transmission

  tasks:
    - name: Ensure the transmission root directory is present
      tags: jfx_clean_td
      stat:
        get_attributes: true
        get_checksum: false
        get_md5: false
        get_mime: false
        path: "{{ transmission_root }}"
      register: _transmission_root

    - block:

        - name: Gather a list of ignore files exceeding transmission retention policy
          find:
            age: "{{ transmission_retention|string + 'd' }}"
            age_stamp: mtime
            file_type: file
            paths: "{{ transmission_root }}"
            patterns: '*.ignore'
            recurse: true
          register: _transmission_find_ignore

        - name: Delete ignore files exceeding transmission retention policy
          become: true
          become_user: couchpotato
          file:
            path: "{{ path }}"
            state: absent
          loop: "{{ _transmission_find_ignore.files|json_query('[].path') }}"
          loop_control:
            label: "{{ path }}"
            loop_var: path

      tags: jfx_clean_td
      when: _transmission_root.stat.exists

    - name: Generate retention epoch time
      tags: jfx_clean_td
      set_fact:
        transmission_epoch: "{{ transmission_now|int - transmission_sec|int }}"
      vars:
        transmission_now: "{{ ansible_date_time.epoch }}"
        transmission_sec: "{{ transmission_retention * 86400 }}"

    - name: Fetch session id from transmission
      tags: jfx_clean_td
      uri:
        method: GET
        status_code: 409
        url: "{{ 'http://' + [transmission_host, transmission_port]|join(':') + '/transmission/rpc' }}"
      register: _transmission_get

    - name: Gather a list of torrents
      tags: jfx_clean_td
      uri:
        body:
          arguments:
            fields: ['id', 'name', 'addedDate']
          method: torrent-get
        body_format: json
        headers:
          X-Transmission-Session-Id: "{{ _transmission_get.x_transmission_session_id }}"
        method: POST
        status_code: 200
        url: "{{ 'http://' + [transmission_host, transmission_port]|join(':') + '/transmission/rpc' }}"
      register: _transmission_torrent_get

    - name: Generate a list from torrent-get return values
      tags: jfx_clean_td
      set_fact:
        transmission_list: "{{ transmission_list|default([]) + _transmission_list }}"
      loop: "{{ _transmission_torrent_get.json.arguments.torrents|json_query('[].{id: id, name: name,  addedDate: addedDate}') }}"
      loop_control:
        label: "{{ t.name }}"
        loop_var: t
      vars:
        _transmission_list:
          - id: "{{ t.id|int }}"
            name: "{{ t.name }}"
            addedDate: "{{ t.addedDate|int }}"

    - name: Delete torrents exceeding transmission retention policy
      tags: jfx_clean_td
      uri:
        body:
          arguments:
            ids: '[ {{ torrent.id }} ]'
            delete-local-data: true
          method: torrent-remove
        body_format: json
        headers:
          X-Transmission-Session-Id: "{{ _transmission_get.x_transmission_session_id }}"
        method: POST
        return_content: true
        status_code: 200
        url: "{{ 'http://' + [transmission_host, transmission_port]|join(':') + '/transmission/rpc' }}"
      register: _ttr
      loop: "{{ transmission_list|default([]) }}"
      loop_control:
        label: "{{ torrent.name }}"
        loop_var: torrent
      when: torrent.addedDate < transmission_epoch
...
